version: "2"
plugins:
  pep8:
    enabled: true
  radon:
    enabled: true
  markdownlint:
    enabled: true
checks:
  file-lines:
    # There is no a real limit imposed, PyLint set it to 1000 lines and raccommanding a refactoring
    # A good development should be between 250 (default of CodeClimate) and 500 lines
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 10
ratings:
  paths:
    - "**.py"
    - "**.md"
exclude_paths:
  - "docs/"
  - "tests/"
  - "packages/"  
  - "resources/language/"
  - "resources/media/"
  - "resources/skins/"
  - "resources/settings.xml"
  - "addon.xml"
  - "LICENSE.md"
  - "requirements.txt"
  - "tox.ini"
